Add events Before/After test group run
Delvin09/TestFrameWork pull request #15
Opened 2024-08-21 09:39 UTC by carbaggios

2024-08-23 07:37 UTC, carbaggios commented
Done. Please review

2024-08-26 18:29 UTC, Delvin09 requested changes

2024-08-26 18:29 UTC, Delvin09 commented on TestFrameWork.Abstractions/TestGroupEventArgs.cs
> +        public required string GroupName { get; init; }
добавь инфы - например полное имя типа и сборки

2024-08-26 18:29 UTC, Delvin09 commented on TestFrameWork.Core/TestGroupInfo.cs
> +                BeforeGroupTestRun?.Invoke(this, e);
а он тут в рекурсию не попадет?
Я думал добавить эти события в Engine, а тут просто перебросить их в Engine.

2024-09-10 09:58 UTC, carbaggios commented on TestFrameWork.Abstractions/TestGroupEventArgs.cs
> +        public required string GroupName { get; init; }
Додав

2024-09-10 09:59 UTC, carbaggios commented on TestFrameWork.Core/TestGroupInfo.cs
> +                BeforeGroupTestRun?.Invoke(this, e);
Прокинув події в TestEngine

2024-09-14 11:19 UTC, Delvin09 approved these changes

2024-09-16 16:12 UTC, merged