Complete Task5.
Delvin09/TestFrameWork pull request #17
Opened 2024-08-27 17:10 UTC by LordMixa

Some change on logic. Add new classes. Return testreport with info of complete tests.

2024-08-29 18:50 UTC, Delvin09 requested changes

2024-08-29 18:50 UTC, Delvin09 commented on TestFrameWork.Core/TestGroupInfo.cs
> +                double time = stopWatch.Elapsed.TotalSeconds;
лучше весь Elapsed сохранить

2024-08-29 18:50 UTC, Delvin09 commented on TestFrameWork.Core/TestInfo.cs
> +        public Exception Run(object subject)
Может TestResult возвращать?, посмотри ПР https://github.com/Delvin09/TestFrameWork/pull/16/files

2024-08-29 18:50 UTC, Delvin09 commented on TestFrameWork.Core/TestInfo.cs
> +        public Exception Run(object subject)
тесты могут завершится с разными статусами, нужно добавить в результат.

2024-08-29 18:50 UTC, Delvin09 commented on TestFrameWork.Core/TestInfo.cs
> +        public Exception Run(object subject)
ну или предусмотреть это

2024-08-31 18:02 UTC, LordMixa commented on TestFrameWork.Core/TestInfo.cs
> +        public Exception Run(object subject)
> тесты могут завершится с разными статусами, нужно добавить в результат.
В TestResult есть строка Status и статусы тестов добавляются в результат и указываются в TestReport по типу: Passed Failed и Unhandled Exception если я правильно понял

2024-09-01 09:58 UTC, Delvin09 requested changes

2024-09-01 09:58 UTC, Delvin09 commented on TestFrameWork.Core/TestEngine.cs
> +            TestReport testReport = new TestReport();
пускай этот метод возвращает репорт

2024-09-01 09:58 UTC, Delvin09 commented on TestFrameWork.Core/TestGroupInfo.cs
> +    public class TestGroupInfo
не совсем понял, зачем паблик

2024-09-01 11:52 UTC, LordMixa commented on TestFrameWork.Core/TestGroupInfo.cs
> +    public class TestGroupInfo
> не совсем понял, зачем паблик

там в TestReport: public void AddTestGroup(TestGroupInfo testGroupResult). Требует public TestGroupInfo

2024-09-01 12:47 UTC, Delvin09 commented
Скорректировал решение, плз, посмотри внимательно, и если нужно подмержи в другую ветку

2024-09-01 18:47 UTC, Delvin09 approved these changes

2024-09-01 18:49 UTC, merged